services:
  ponder-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./ponder-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ponder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      ponder-db:
        condition: service_healthy
    ports:
      - "42069:42069"
    environment:
      NODE_ENV: development
      PONDER_RPC_URL_8453: ${PONDER_RPC_URL_8453}
      PONDER_RPC_URL_42220: ${PONDER_RPC_URL_42220}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ponder-db:5432/${POSTGRES_DB}"
    command: [ "npm", "run", "dev" ]
